### PR TITLE
Mass assignment fix

### PR DESCRIPTION
**Pull request by karlfreeman**
Rails 3.2.2 with config.active_record.whitelist_attributes = true breaks functionality

### CODE REVIEW

**Comment by karlfreeman** [comment]
should close #35

**Comment by ZenCocoon** [comment]
+1, would be happy to have this merged.

**Comment by emptyflask** [comment]
+1

**Comment by karlfreeman** [comment]
Any chance this could be scheduled to be pulled in on the next version bump? [Rails 3.2.3](http://weblog.rubyonrails.org/2012/3/30/ann-rails-3-2-3-has-been-released/) has been out for a while now and needs this change :)

**Comment by winfred** [comment]
yes plz

**Comment by colszowka** [comment]
+1 :)

**Comment by jphenow** [comment]
This should get merged I think?

**Comment by ZenCocoon** [comment]
@wireframe could you please merge this commit, it currently push people to disable `config.active_record.whitelist_attributes = true` which increase potential security issues.

**Comment by karlfreeman** [comment]
thanks @ZenCocoon :)

**Comment by wireframe** [comment]
thanks for bumping this pull request.  I was out of the office when the original pull request was filed, and so it wasn't on my radar.

I've incorporated the patch with a few modifications and pushed v1.1.2 to rubygems.

**Comment by karlfreeman** [comment]
@wireframe No problem :+1:

**Comment by ZenCocoon** [comment]
@wireframe brilliant, thanks for the merge.

**Pull request closed without merging**
