### PR TITLE
Mega-fix bundle

### PR DESCRIPTION
**Pull request by philsturgeon**
Now, I know normally single changes and single bug-fixes are required to be sent in one at a time but there seems to be a few valid fixes floating around for various problems that the original authors are not sending in to you. 

This gem has not been updated in a month and looking at your network some errors are being fixed multiple times.

I've had various problems and by combining all of these into a single location I have got my gem working nicely on Rack 1.3.3, Rails 3.1 and Ruby 1.9.2 with the very latest OAuth 2 gem from intridea.

Please can you merge this whole bunlde of commits, as it fixes a series of issues. Right now your gem does not follow the final spec so it breaks :)

### CODE REVIEW

**Comment by renatovico** [comment]
+1

**Comment by wireframe** [comment]
thanks for putting this together.

honestly, the only thing i'm hesitant with this change is exposing an external UI for managing clients.  IMO, this is _extremely_ application specific and well outside the definition of the oauth2 spec (intentionally).  each application has it's own requirements around oauth2 client creation (ex: clients may be directly associated to the owning user), and I find it difficult to generalize it for use as a drop in gem.  

not to mention the security implications which are not addressed here (ex: any user can edit any client).

**Comment by philsturgeon** [comment]
Yeah that one slipped in hang about.

**Comment by philsturgeon** [comment]
I've removed the client gui and an errorneous commit of my own from this pull request. Please merge.

**Comment by wireframe** [comment]
thanks.  merged changes and released v0.3.8 gem.

**Pull request merged**
